### ISSUE TITLE
VCHs are shown in OFF state despite rescan

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1353]
1.3.1 OVA: vic-v1.3.1-rc1-3256-b1b156e5.ova

Steps:
1. Upgrade OVA from 1.3.0 to 1.3.1
2. The VCHs were added to project lg
3. Harbor service did not come up as expected, which is tracked by https://github.com/vmware/vic-product/issues/1351 
4. Destroyed  VCHs and their containers
5. Created new VCHs with same IP addresses using vic-machine-linux but could not download the ca.crt due to UI not showing the download link(so used the pre-upgrade 1.3 OVA's ca.crt)
![image](https://user-images.githubusercontent.com/25006749/35562911-f48036d0-05da-11e8-9de4-f2d7cca9981c.png)
6. Logged into Admiral and seeing all VCHs in OFF state
![image](https://user-images.githubusercontent.com/25006749/35563062-7f25bd1e-05db-11e8-8241-e38161acde6d.png)
7. Rescan did not help and admiral log is complaining of
```
[66989][W][2018-01-30T09:35:25.289Z][39][8282/adapters/host-docker-service][fail][Fail: java.lang.Exception: No route to host: /10.197.37.154:2376; Reason: {"message":"No route to host: /10.197.37.154:2376","stackTrace":["sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)","sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)","io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)","io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)","io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":500,"details":["SHOULD_RETRY"],"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.197.37.154:2376
```
8. Removed one VCH from Admiral and added again, after which the status showed as ON.
![image](https://user-images.githubusercontent.com/25006749/35563283-382f1fd0-05dc-11e8-8e44-0e1fa8137ae6.png)

I was expecting that since VCHs were recreated with the same IP addresses, Admiral would reconnect them. Is user expected to remove and add VCHs to Admiral?

**Comment by lgayatri** [comment]
@sergiosagu @mdubya66

**Comment by sergiosagu** [comment]
@lgayatri (cc @lazarin @martin-borisov )

> I was expecting that since VCHs were recreated with the same IP addresses, Admiral would reconnect them.

Does "recreate a VCH" generate new SSL certificate or they are pre-configured somehow?
If the SSL certificates are regenerated then, even the new VCHs keep the old IP addresses, Admiral won't be able to contact them... so they'll remain in OFF. Maybe if you can attach the logs we can investigate it a bit more.

> Is user expected to remove and add VCHs to Admiral?

Maybe in this case it won't be needed to remove and add them again but just to try to edit them and see if the dialog to accept the new SSL certificate appears. But yes, if the SSL certificate has changed, it's expected to have some human interaction to accept it (if it's not trusted by default).

**Comment by lgayatri** [comment]
@sergiosagu , the SSL cert did not change. I edited one of the VCH which is OFF and clicked Save.  There was no ask to accept the new SSL certificate.

Admiral logs are attached here for your perusal.

[xenonHost.0.zip](https://github.com/vmware/vic-product/files/1677490/xenonHost.0.zip)

**Comment by sergiosagu** [comment]
Thanks! OK, having a quick look at the logs I've picked the host 10.197.37.155, that according to the screenshot is still OFF.

In the logs I've seen how everything is fine. And then the following exception appears frequently (not only for this host but for pretty much all the hosts):

```
[68280][W][2018-01-30T09:40:25.469Z][38][8282/adapters/host-docker-service][fail][Fail: java.lang.Exception: No route to host: /10.197.37.155:2376; Reason: {"message":"No route to host: /10.197.37.155:2376","stackTrace":["sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)","sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)","io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)","io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)","io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":500,"details":["SHOULD_RETRY"],"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
	at com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.fail(AbstractDockerAdapterService.java:374)
	at com.vmware.admiral.adapter.docker.service.DockerHostAdapterService.lambda$getHostPatchCompletionHandler$16(DockerHostAdapterService.java:501)
	...
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.197.37.155:2376
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 8 more
Caused by: java.net.NoRouteToHostException: No route to host
	... 12 more
]
```

That's probably for the period of time when you destroyed the host and Admiral couldn't contact it. Then at some point the following exception appears also frequently (it's not connected to a specific host in the trace, but I'm pretty sure that it appears for pretty much all the hosts again):

```
[89877][W][2018-01-30T11:35:31.367Z][39][8282/adapters/host-docker-service][fail][Fail: java.lang.Exception: javax.net.ssl.SSLHandshakeException: General SSLEngine problem; Reason: {"message":"javax.net.ssl.SSLHandshakeException: General SSLEngine problem","stackTrace":["io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)","io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)","io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)","io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)","io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)","io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":400,"details":["SHOULD_RETRY"],"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
	at com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.fail(AbstractDockerAdapterService.java:374)
	at com.vmware.admiral.adapter.docker.service.DockerHostAdapterService.lambda$getHostPatchCompletionHandler$16(DockerHostAdapterService.java:501)
	...
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	... 15 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
	... 17 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	... 19 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	... 27 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	... 36 more
]
```

And that exception exactly looks like a SSL certificate problem. Are you sure that if you create a host, destroy it and create it again the SSL certificate of the :2376 endpoint is exactly the same? It's possible that both certificates are valid for the same IP/hostname (e.g. https://10.197.37.155:2376) but the randomly created certificates will be different (e.g. different serial numbers).

> I edited one of the VCH which is OFF and clicked Save. There was no ask to accept the new SSL certificate.

This can be OK and working as designed at the moment. Since there's already a SSL certificate configured for the host, maybe the UI doesn't show the warning because we don't check whether it has changed or not. Well, I've just seen that the edit host dialog of a VCH cluster does not have a Verify button, whereas in a Docker cluster you have a Verify button in the same dialog... but that's independent from the issue described in the main thread.

**Comment by lgayatri** [comment]
@sergiosagu . Once the VCHs are added to a project and then recreated, the status gets marked as OFF.

![image](https://user-images.githubusercontent.com/25006749/35797963-5d8c645e-0a87-11e8-80a3-1d790770cf34.png)

Can we enhance the "Rescan" here to reconnect with Admiral and show the correct status?

**Comment by lazarin** [comment]
Just logged to that system:
![screenshot at 2018-02-05-11-50-30](https://user-images.githubusercontent.com/676880/35798254-e4fdda5c-0a6a-11e8-9b7c-c343ff73eb14.png)

**Comment by sergiosagu** [comment]
@lgayatri 
> Once the VCHs are added to a project and then recreated, the status gets marked as OFF.

What does that mean exactly? You added to a project successfully and they are up and running, and then you destroy & create them again without removing them from the project? If that's the case, then I think that's the expected behavior of marking them as OFF.

> After few minutes, they all turned ON automatically, which was not the case with upgrade scenario.

Well, that's interesting. Few minutes means that probably the data collection was automatically triggered. I don't think that the upgrade (especially from 1.3.0 to 1.3.1) has anything to do with the hosts and their states, or the way the reconnections are tried. cc @gmuleshkov 
And just to clarify it, now you are trying with a brand new 1.3.1 environment? Or is it post-1.3.1?

We should take a look at the logs of this 2nd scenario to see if there's also the same pattern of exceptions (NoRouteToHostException + SSLHandshakeException) or not.

**Comment by zjs** [comment]
@lgayatri, is this issue still relevant?
