### ISSUE TITLE
VIC appliance upgrade failed from 1.3.1 to 1.4 Rc2 as admiral.service failed to start

### ISSUE THREAD

**Issue by hchundu-vmw** [vmware/vic-product#1666]
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version:6.5 U1
- Embedded or external PSC:Embedded
- Filename of the OVA you deployed:vic-v1.4.0-rc2-4741-f02b3258.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): ovftool
- Does the VIC appliance recieve configuration by DHCP? Static
- What stage of the Appliance Lifecycle is the VIC appliance in? Appliance deployed succesfully and the upgrade failed 
 
- Attach the VIC appliance support bundle  -- vic_appliance_logs_2018-04-28-11-53-02.tar.gz
  

OPTIONAL, but helpful:

- IP address of VIC appliance: 10.197.37.130 (old vic appliance on 1.3.1  is 10.197.37.132)
- Hostname of VIC appliance: vic-st-h2-130.eng.vmware.com
- IP address of vCenter Server: 10.133.146.15
- Hostname of vCenter Server:wdc-stvc3944-146-dhcp15.eng.vmware.com

Bug Report Detailed Information
-------------------------------
Vic appliance upgrade failed from 1.3.1 to 1.4.0

Following is the procedure followed 

1)Deployed 1.3.1 vic appliance

2)Created 50 VCH's and 2600 containers

3)Created 50 projects

4)Created a network from admiral ui and couple of templates 

5)Added all VCH's to admiral

Following is the error in logs when the upgrade failed

2018-04-28 11:16:23 [=] Finished preparing upgrade environment
2018-04-28 11:16:23 [=]
-------------------------
Starting Admiral Upgrade 2018-04-28 11:10:17 +0000 UTC

2018-04-28 11:16:23 [=] Performing pre-upgrade checks
2018-04-28 11:16:23 [=] Starting Admiral upgrade
Job for admiral.service failed because the control process exited with error code. See "systemctl status admiral.service" and "journalctl -xe" for details.
2018-04-28 11:17:53 [=]
2018-04-28 11:17:53 [=] -------------------------
2018-04-28 11:17:53 [=] Upgrade failed.
2018-04-28 11:17:53 [=] Please save /var/log/vmware/upgrade.log and contact VMware support.
2018-04-28 11:17:53 [=] -------------------------
2018-04-28 11:17:53 [=]
                                                                                                                                          

From the admiral logs we have the following error

[280][I][2018-04-28T11:17:08.140Z][28][8282/config/compute-initial-boot][countDown][Stopping initial boot service: /config/compute-initial-boot]
[281][I][2018-04-28T11:17:08.751Z][31][8282/resources/hosts-data-collections/host-info-data-collection][lambda$startAndCreateCallbackHandlerService$34][Callback task created with uri: https://172.17.0.3:8282/request/callback-handler/347b3ce8-b880-45e2-b13f-63420b87a3f7, https://172.17.0.3:8282/request/callback-handler/347b3ce8-b880-45e2-b13f-63420b87a3f7]
[282][I][2018-04-28T11:17:08.753Z][24][8282/resources/hosts-data-collections/host-info-data-collection][lambda$startAndCreateCallbackHandlerService$34][Callback task created with uri: https://172.17.0.3:8282/request/callback-handler/9cdffcb0-4959-4f4a-ab61-545022767918, https://172.17.0.3:8282/request/callback-handler/9cdffcb0-4959-4f4a-ab61-545022767918]
[283][W][2018-04-28T11:17:08.754Z][31][8282/resources/hosts-data-collections/host-info-data-collection][lambda$updateContainerHostInfo$29][Failed request host info: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: https://172.17.0.3:8282/adapters/host-docker-service
        at com.vmware.xenon.common.Operation.failServiceNotFound(Operation.java:448)
        at com.vmware.xenon.common.Operation.failServiceNotFound(Operation.java:434)
        at com.vmware.xenon.common.ServiceHost.queueOrForwardRequest(ServiceHost.java:3956)
        at com.vmware.xenon.common.ServiceHost.handleRequestWithAuthContext(ServiceHost.java:3658)
        at com.vmware.xenon.common.ServiceHost.lambda$checkAndPopulateAuthzContext$34(ServiceHost.java:3621)
        at com.vmware.xenon.common.Operation.lambda$nestCompletion$2(Operation.java:1386)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1340)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1239)
        at com.vmware.xenon.services.common.AuthorizationContextServiceHelper.queueRequest(AuthorizationContextServiceHelper.java:159)
        at com.vmware.xenon.services.common.AuthorizationContextService.queueRequest(AuthorizationContextService.java:77)
        at com.vmware.xenon.common.ServiceHost.queueOrScheduleRequestInternal(ServiceHost.java:4297)
        at com.vmware.xenon.common.ServiceHost.queueOrScheduleRequest(ServiceHost.java:4266)
        at com.vmware.xenon.common.ServiceHost.checkAndPopulateAuthzContext(ServiceHost.java:3623)
        at com.vmware.xenon.common.ServiceHost.checkAndPopulateAuthContext(ServiceHost.java:3552)
        at com.vmware.xenon.common.ServiceHost.handleRequest(ServiceHost.java:3542)
        at com.vmware.admiral.host.ManagementHost.handleRequest(ManagementHost.java:599)
        at com.vmware.xenon.common.ServiceHost.handleRequest(ServiceHost.java:3510)
        at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.sendRequest(NettyHttpServiceClient.java:272)
        at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.send(NettyHttpServiceClient.java:253)
        at com.vmware.xenon.common.ServiceHost.sendRequest(ServiceHost.java:4403)
        at com.vmware.xenon.common.StatefulService.sendRequest(StatefulService.java:1773)
        at com.vmware.admiral.compute.container.ContainerHostDataCollectionService.updateContainerHostInfo(ContainerHostDataCollectionService.java:896)
        at com.vmware.admiral.compute.container.ContainerHostDataCollectionService.lambda$updateContainerHostInfo$27(ContainerHostDataCollectionService.java:883)
        at com.vmware.admiral.compute.container.ContainerHostDataCollectionService.lambda$startAndCreateCallbackHandlerService$34(ContainerHostDataCollectionService.java:1017)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1340)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1239)

**Comment by hchundu-vmw** [comment]
[vic_appliance_logs_2018-04-28-11-53-02.tar.gz](https://github.com/vmware/vic-product/files/1957701/vic_appliance_logs_2018-04-28-11-53-02.tar.gz)

**Comment by lazarin** [comment]
I've logged on into the appliance, the issue is still there
The problem is that the machine cannot resolve its own hostname which is leading to endless loop starting and then checking the first container - admiral

**Comment by andrewtchin** [comment]
This issue was caused by a problem with DNS in the environment
