### ISSUE TITLE
Admiral fails to open when VCSA is in Embedded linked mode

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1871]
##### For bug reports, please include the information below:

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.8.2
- Embedded or external PSC: EMBEDDED LINKED MODE
- Filename of the OVA you deployed: vic-v1.4.1-rc2-5496-f2fdac75.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): ovftool
- Does the VIC appliance recieve configuration by DHCP?No, static 
- What stage of the Appliance Lifecycle is the VIC appliance in? 8282 port - admiral port fails to open

- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
Attached.
[vic_appliance_logs_2018-07-02-09-04-44.tar.gz](https://github.com/vmware/vic-product/files/2154566/vic_appliance_logs_2018-07-02-09-04-44.tar.gz)

##### For feature requests/user stories, please include the information below:
Registration with VCSA successful
![image](https://user-images.githubusercontent.com/25006749/42155529-3fb699fc-7e06-11e8-959b-b86921c608d2.png)

Admiral cannot be opened:
![image](https://user-images.githubusercontent.com/25006749/42155777-ed48c02c-7e06-11e8-91b3-464b32941612.png)

admiral log snippet:
```
[524][I][2018-07-02T08:46:19.799Z][21][8282/resources/epz-periodic-enumeration][doTrigger][Periodic refresh]
[525][W][2018-07-02T08:46:58.310Z][718][8282/auth/psc/callback][redirectToSamlSso][Could not generate redirect URL: java.lang.IllegalStateException: SsoManager has not been initialized
        at com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.getInstance(SamlManager.java:100)
        at com.vmware.admiral.auth.idm.psc.saml.sso.authentication.SamlRequestSender.<init>(SamlRequestSender.java:45)
        at com.vmware.admiral.auth.idm.psc.saml.util.SsoUriGenerator.generateRedirectUrl(SsoUriGenerator.java:47)
        at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSamlSso(PscAuthenticationService.java:498)
        at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.redirectToSso(PscAuthenticationService.java:491)
        at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handleGet(PscAuthenticationService.java:474)
        at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:120)
        at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)
        at com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$45(ServiceHost.java:4301)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
@zjs @martin-borisov @renmaosheng

**Comment by hickeng** [comment]
@lgayatri Thanks for the finding! Is this a regression, or a new test?

**Comment by lgayatri** [comment]
New test. We will have to support this configuration for next releases.

**Comment by lgayatri** [comment]
@martin-borisov , can you please let us know if we can address this bug soon. Embedded linked mode configuration is being preferred over external PSC.

@renmaosheng @jitinkumar2018

**Comment by lgayatri** [comment]
@renmaosheng Embedded linked mode is in 6.7 as well and we have the same issue. I filed this bug on 6.8.2 since I had the setup handy.

**Comment by sergiosagu** [comment]
The problem seems to be in the VA configuration...

The admiral_psc-config contains
```
...
domain-controller=cloud02-w3.stls.local
domain-controller.port=443
...
```
which seems correct.

But when Admiral container tries to access that host, it fails with unknown host. The xenonHost.0.log cotains
```
[347][S][2018-07-02T06:31:13.675Z][33][8282/][lambda$initialize60$0][PscSettings : java.net.UnknownHostException: cloud02-w3.stls.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at com.vmware.admiral.auth.idm.psc.saml.sso.platform.security.SslCertificateResolver.connect(SslCertificateResolver.java:96)
	at com.vmware.admiral.auth.idm.psc.saml.sso.platform.security.CertificateUtil.getSsoCertificate(CertificateUtil.java:327)
	at com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.<init>(SamlManager.java:133)
	at com.vmware.admiral.auth.idm.psc.saml.util.SamlManager.createOrGetInstance(SamlManager.java:83)
	at com.vmware.admiral.auth.idm.psc.PscAuthConfigProvider.lambda$initialize60$0(PscAuthConfigProvider.java:91)
	at java.lang.Thread.run(Thread.java:748)
]
```
and from that failure, since the access to PSC couldn't be initialized, all the next attempts to access PSC fail with
```
[394][W][2018-07-02T06:41:33.020Z][104][8282/auth/psc/callback][redirectToSamlSso][Could not generate redirect URL: java.lang.IllegalStateException: SsoManager has not been initialized
```

The `/etc/hosts` (from an newer VA deployment) contains only
```
# Begin /etc/hosts (network card version)

::1         ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1   localhost

# End /etc/hosts (network card version)
```
and the `/etc/resolv.conf` just
```
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 10.162.204.1
nameserver 10.166.1.1
```

With those settings, Admiral (within the Admiral container) can't resolve the hostname `cloud02-w3.stls.local`. Which I'm not sure it's an issue of that "Embedded linked mode" or something else.

Who can take a look at it from the VA side? @martin-borisov @lgayatri @renmaosheng @hickeng

**Comment by renmaosheng** [comment]
@lgayatri is this domain name 'cloud02-w3.stls.local' created by our test ? thanks.

**Comment by lgayatri** [comment]
Hi @renmaosheng, stls.local is the VCSA's domain name and to get it resolved, we have added entries in host file.

**Comment by martin-borisov** [comment]
Not sure why this was assigned to me. It should be handled in the OVA.

**Comment by lgayatri** [comment]
I tried embedded linked mode configuration with 6.7U1 build and excited to share the VIC OVA registration succeeded. I could even open the Admiral UI. 

However, I could not get VCSA 6.8.2 working with 1.4.3
@renmaosheng

**Comment by zjs** [comment]
> I tried embedded linked mode configuration with 6.7U1 build and excited to share the VIC OVA registration succeeded. I could even open the Admiral UI.

Given this, I think we can defer this from 1.4.3.

**Comment by renmaosheng** [comment]
@clouderati what is our inter-op matrix for VIC 1.5? thanks a lot.
