### ISSUE TITLE
VIC 1.4.4 H5 plugin is not being installed (install UI plugin radio button) during VIC registration with VC 6.7 U2 

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2196]
Bug Report Basic Information
REQUIRED:

vCenter Server version: 6.7 U2
vCenterBuild: 10882746
Embedded or external PSC: No
Filename of the OVA you deployed: vic-v1.4.4-6375-0a6da3d4
How was the OVA deployed? Ovftool
Does the VIC appliance receive configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Initialization Stage

Bug Details:
VIC H5 plugin does not get installed on the VC even though the radio button "Install UI plugin" was selected in the VIC to VC registration wizard.

@lgayatri @renmaosheng @reasonerjt

**Comment by renmaosheng** [comment]
Meina,
     could you please take a look? thanks.

**Comment by zhoumeina** [comment]
@pureshine, could you please take a look?I can help you investigate together.

**Comment by zhoumeina** [comment]
@jitinkumar2018,  please try to login again. Need to logout and login again the plugin will appear.

**Comment by jitinkumar2018** [comment]
I tried logging in and logging out and plugin does not appear. Please note: it is a nimbus VC

**Comment by pureshine** [comment]
@jitinkumar2018 We tested on numbus vc, the h5 plugin can be displayed on the menu, could you please  clear your browser cache and try to redeploy ova to reinitialize and try to log in again twice.
![image](https://user-images.githubusercontent.com/40712758/49847042-1a0cb000-fe09-11e8-9136-3edd05e56d3b.png)

**Comment by pureshine** [comment]
@jitinkumar2018 Could you please provide your vc environment? I will test it again using your environment.thanks

**Comment by jitinkumar2018** [comment]
vc IP: 10.193.36.210

**Comment by pureshine** [comment]
vsphere-client-serenity/com.vmware.vic-1.4.4.1405 org.osgi.service.subsystem.SubsystemException: org.osgi.service.resolver.ResolutionException: Unable to resolve /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/com.vmware.vic-1.4.4.1405/com.vmware.vic-1.4.4.1405.esa/vic.war: missing requirement org.apache.aries.subsystem.core.archive.ImportPackageRequirement: namespace=osgi.wiring.package, attributes={}, directives={filter=(&(osgi.wiring.package=org.springframework.web.servlet)(&(version>=3.1.4)(version<=4.3.17.RELEASE_VMWARE))), resolution=mandatory}, resource=/etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/com.vmware.vic-1.4.4.1405/com.vmware.vic-1.4.4.1405.esa/vic.war
        at org.apache.aries.subsystem.core.internal.Utils.handleTrowable(Utils.java:117)
        at org.apache.aries.subsystem.core.internal.SubsystemResource.computeDependencies(SubsystemResource.java:398)
        at org.apache.aries.subsystem.core.internal.SubsystemResource.computeDependencies(SubsystemResource.java:363)
        at org.apache.aries.subsystem.core.internal.SubsystemResource.<init>(SubsystemResource.java:101)
        at org.apache.aries.subsystem.core.internal.SubsystemResource.<init>(SubsystemResource.java:91)
        at org.apache.aries.subsystem.core.internal.InstallAction.run(InstallAction.java:60)
        at org.apache.aries.subsystem.core.internal.InstallAction.run(InstallAction.java:27)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.aries.subsystem.core.internal.BasicSubsystem.install(BasicSubsystem.java:677)
        at org.apache.aries.subsystem.core.internal.BasicSubsystem.install(BasicSubsystem.java:730)
        at org.apache.aries.subsystem.core.internal.BasicSubsystem.install(BasicSubsystem.java:304)
        at org.apache.aries.subsystem.core.internal.BasicSubsystem.install(BasicSubsystem.java:299)
        at org.apache.aries.subsystem.core.internal.BasicSubsystem.install(BasicSubsystem.java:71)
        at com.vmware.vise.extensionfw.impl.OsgiBundleDeployer$SubsystemInstallerTask.run(OsgiBundleDeployer.java:606)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/com.vmware.vic-1.4.4.1405/com.vmware.vic-1.4.4.1405.esa/vic.war: missing requirement org.apache.aries.subsystem.core.archive.ImportPackageRequirement: namespace=osgi.wiring.package, attributes={}, directives={filter=(&(osgi.wiring.package=org.springframework.web.servlet)(&(version>=3.1.4)(version<=4.3.17.RELEASE_VMWARE))), resolution=mandatory}, resource=/etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/com.vmware.vic-1.4.4.1405/com.vmware.vic-1.4.4.1405.esa/vic.war
        at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:368)
        at org.apache.aries.subsystem.core.internal.SubsystemResource.computeDependencies(SubsystemResource.java:393)
        ... 13 common frames omitted

**Comment by zhoumeina** [comment]
The org.springframework.web.servlet) need to be version>=3.1     <=4.3.17. Seems in vc 6.7 u2, it upgrade this depencency

**Comment by zhoumeina** [comment]
@jitinkumar2018 , could you please provide vcenter build number? let me try to install it locally.

**Comment by jitinkumar2018** [comment]
Sure, Vcenter build: 10882746

**Comment by zhoumeina** [comment]
I found this build in : https://buildweb.eng.vmware.com/ob/10882746/
However, not sure how to download it. Do you know?

**Comment by jitinkumar2018** [comment]
I am not quite sure. I shall let you know if I get my hands on this build

**Comment by lgayatri** [comment]
@zhoumeina Build is available now.

**Comment by zhoumeina** [comment]
@jitinkumar2018 , after we investigate the vc 6.7 library, many libs have been changed which are not adapt to our api. I am afraid we can not support u2 version in short time. I think this need to be delayed and target in later release. @renmaosheng

**Comment by lgayatri** [comment]
@stuclem lets document this

**Comment by stuclem** [comment]
OK, thanks @renmaosheng

**Comment by renmaosheng** [comment]
I should have said that 6.7 U2 will be GAed later than VIC 1.5, so we have to use our next patch after 1.5 to support 6.7 U2. thanks.
