### ISSUE TITLE
Unable to Register VIC appliance to 7.0 VC via API

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2550]
Bug Report Basic Information

VC Build:  https://buildweb.eng.vmware.com/ob/15610183/
ESX Build: https://buildweb.eng.vmware.com/ob/15525992/
Embedded or external PSC: Embedded
Vic Builds used: v1.5.4-7589-e70af4fe.ova, vic-dev-v1.5.5-rc1-7701-fb00e93c.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Registration

Bug Report Detailed Information
What operation was being performed when the failure was noticed?
Registration of VIC appliance with VC via rest API. Tried with VIC 1.5.4 and VIC 1.5.5 RC1

Rest call: 
curl -k -w '%{http_code}' -d @payload.json ht://10.197.37.181:9443/register  ( VIC 1.5.5 RC1 )
curl -k -w '%{http_code}' -d @payload.json ht://10.197.37.182:9443/register  ( VIC 1.5.4 )

payload.json
`{"target":"w2hs2-rdp04.eng.vmware.com","user":"Administrator@vsphere.local","password":"Admin!23","thumbprint":"A3:C4:2A:26:1D:D3:F4:B7:B0:7D:4C:16:4B:EC:B6:0E:C5:3B:85:97","vicpassword":"Admin!23"}`

$ journalctl -f

`Feb 19 18:32:38 vic-st-h2-182.eng.vmware.com toolbox[338]: 2020/02/19 18:32:38 SendGuestInfo 0: xdr:encode: type 'invalid' is not valid
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.553Z DEBUG [BEGIN]  [vic-product/installer/fileserver/routes.RegisterHandler:40]
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.553Z DEBUG op=1644.6: [NewOperation] op=1644.6 [vic-product/installer/fileserver/routes.RegisterHandler:44]
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.611Z DEBUG [BEGIN]  [vic-product/installer/lib.(*LoginInfo).VerifyLogin:43]
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.612Z INFO  op=1644.6: server URL: w2hs2-rdp04.eng.vmware.com
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.612Z DEBUG op=1644.6: Creating VMOMI session with thumbprint A3:C4:2A:26:1D:D3:F4:B7:B0:7D:4C:16:4B:EC:B6:0E:C5:3B:85:97
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.747Z DEBUG Session Environment Info:
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.747Z DEBUG op=1644.6: vSphere resource cache populating...
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.754Z DEBUG op=1644.6: Cached dc:
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.760Z DEBUG op=1644.6: Cached cluster:
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.781Z DEBUG op=1644.6: Cached pool:
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.783Z DEBUG op=1644.6: Cached folders:
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.783Z DEBUG op=1644.6: Error count populating vSphere cache: (1)
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.783Z DEBUG [ END ]  [vic-product/installer/lib.(*LoginInfo).VerifyLogin:43] [171.977089ms]
Feb 19 18:32:44 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:44.784Z INFO  op=1644.6: Validation succeeded
Feb 19 18:32:45 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:45.544Z DEBUG op=1644.6: successfully attached the product tag
Feb 19 18:32:45 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:45.547Z INFO  op=1644.6: vCenter user: Administrator@vsphere.local
Feb 19 18:32:45 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:45.547Z INFO  op=1644.6: PSC instance: w2hs2-rdp04.eng.vmware.com
Feb 19 18:32:45 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:45.547Z INFO  op=1644.6: PSC domain: vsphere.local
Feb 19 18:32:45 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:45.549Z INFO  op=1644.6: PSC Out of the box users. CreateUsers: True, FoundCreateUsers: true, Prefix: vic
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:48.343Z INFO  op=1644.6: Error running PSC register command for harbor: [0][I][2020-02-19T18:32:45.737Z][1][SsoPscCommand][register][Initializing...]
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: [1][I][2020-02-19T18:32:45.746Z][1][SsoPscCommand][register][Registering...]
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: [2][I][2020-02-19T18:32:45.778Z][1][SsoPscCommand][deleteFile][Removal of file: '/etc/vmware/psc/harbor/psc-config.keystore' result: true]
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Exception in thread "main" com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientException: Server returned 'request expired' less than 0 seconds after request was issued, but it shouldn't have expired for at least 600 seconds.
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClientFactoryImpl.java:156)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminFacade.registerOrRetrieveSolutionUser(SsoAdminFacade.java:172)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.saml.util.SsoPscCommand.register(SsoPscCommand.java:83)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.util.PscCommand.execute(PscCommand.java:43)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.util.PscCommand.main(PscCommand.java:56)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Caused by: com.vmware.vim.sso.client.exception.TimeSynchronizationException: Server returned 'request expired' less than 0 seconds after request was issued, but it shouldn't have expired for at least 600 seconds.
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.checkTimeSyncronization(SecurityTokenServiceImpl.java:902)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.executeRoundtrip(SecurityTokenServiceImpl.java:858)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl.acquireToken(SecurityTokenServiceImpl.java:149)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClientFactoryImpl.java:140)
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]:         ... 4 more
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:48.343Z DEBUG op=1644.6: exit status 1
Feb 19 18:32:48 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1642]: Feb 19 2020 18:32:48.348Z DEBUG [ END ]  [vic-product/installer/fileserver/routes.RegisterHandler:40] [3.795254013s]
Feb 19 18:32:54 vic-st-h2-182.eng.vmware.com wait_for_file.sh[181]: File /etc/vmware/psc/admiral/psc-config.properties does not yet exist. sleeping 30 seconds...`

VIC Appliance Support Bundle:

[VIC1.5.5_RC1_vic_appliance_logs_2020-02-19-19-04-55.tar.gz](https://github.com/vmware/vic-product/files/4226764/VIC1.5.5_RC1_vic_appliance_logs_2020-02-19-19-04-55.tar.gz)
[VIC1.5.4_vic_appliance_logs_2020-02-19-18-58-31.tar.gz](https://github.com/vmware/vic-product/files/4226765/VIC1.5.4_vic_appliance_logs_2020-02-19-18-58-31.tar.gz)

**Comment by jitinkumar2018** [comment]
@renmaosheng @luwang-vmware

**Comment by jitinkumar2018** [comment]
Closing bug as there was a time skew between VC and VIC appliances. NTP server wasnt running on the ESX. After fixing time skew, was able to register appliance to VC
