### ISSUE TITLE
Failed to register with PSC - OVA 1.5.8

### ISSUE THREAD

**Issue by gitloy** [vmware/vic-product#2611]
#### Summary
Installation failed: Failed to register with PSC. Please check the PSC settings provided and try again

##### vSphere and vCenter Server version
vSphere:  VMware ESXi, 6.7.0, 15160138
vCenter:  Server 6.7.0.48000

##### VIC Appliance version
vic-v1.5.8-7942-4cc5e276.ova

##### Configuration

- EmbeddedPSC:
- How was the OVA deployed? HTML5 
- Does the VIC appliance receive configuration by DHCP?  Yes
- What [stage of the Appliance Lifecycle][1] is the VIC appliance in?  OVA is deployed, configuration step not completing
- IP address of VIC appliance: 
- Hostname of VIC appliance:  vcntr-01-wat.ourmagnet.net
- IP address of vCenter Server:
- Hostname of vCenter Server:  vIntCont-01-wat

#### Details
When working through the Complete VIC appliance installation step I end up with the following error. All default options were used for the set up of the appliance.

Error:  "Installation failed: Failed to register with PSC. Please check the PSC settings provided and try again"

##### Steps to reproduce
This occurs each time I enter the necessary details

#### Logs
Below I believe is the relevant log detail

The lines that stick out for me contain

Error running PSC register command for harbor
Failed to load class "org.slf4j.impl.StaticLoggerBinder

Jan 19 15:40:24 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:24.348Z INFO  op=1762.32: PSC Out of the box users. CreateUsers: True, FoundCreateUsers: true, Prefix
: vic

Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.823Z INFO  op=1762.32: Error running PSC register command for harbor: [0][I][2022-01-19T15:40:24.5
38Z][1][SsoPscCommand][register][Initializing...]

Jan 19 15:40:26 localhost start_fileserver.sh[1759]: [1][I][2022-01-19T15:40:24.546Z][1][SsoPscCommand][register][Registering...]
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: [2][I][2022-01-19T15:40:24.570Z][1][SsoPscCommand][deleteFile][Removal of file: '/etc/vmware/psc/harbor/psc-config.keys
tore' result: true]

Jan 19 15:40:26 localhost start_fileserver.sh[1759]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

Jan 19 15:40:26 localhost start_fileserver.sh[1759]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Exception in thread "main" com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientException: General SSO failure.
 Invalid host, port or tenant.
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClient
FactoryImpl.java:148)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminFacade.registerOrRetrieveSolutionUser(SsoAdminFacade.
java:172)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.saml.util.SsoPscCommand.register(SsoPscCommand.java:83)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.util.PscCommand.execute(PscCommand.java:43)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.util.PscCommand.main(PscCommand.java:56)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Caused by: com.vmware.vim.sso.admin.exception.InternalError: General failure.
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.execute(VmomiClientCommand.java:211)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.executeEnsuringNoDomainError(VmomiClientComman
d.java:217)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl.createServiceContent(AdminClientImpl.java:341)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl.<init>(AdminClientImpl.java:107)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.VmomiClientFactory.createAdminClient(VmomiClientFactory.java:64)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.VmomiClientFactory.createAdminClient(VmomiClientFactory.java:54)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClient
FactoryImpl.java:123)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         ... 4 more
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Caused by: com.vmware.vim.vmomi.client.common.UnexpectedStatusCodeException: Unexpected status code: 404
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.Response$Status.getStatus(Response.java:58)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.http.impl.HttpExchangeBase.parseResponse(HttpExchangeBase.java:150)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.http.impl.HttpExchange.run(HttpExchange.java:48)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.http.impl.HttpProtocolBindingBase.executeRunnable(HttpProtocolBindingBase.java:2
26)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.http.impl.HttpProtocolBindingImpl.send(HttpProtocolBindingImpl.java:110)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl$CallExecutor.sendCall(MethodInvocationHa
ndlerImpl.java:613)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl$CallExecutor.executeCall(MethodInvocatio
nHandlerImpl.java:594)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.completeCall(MethodInvocationHandlerImpl
.java:345)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.invokeOperation(MethodInvocationHandlerI
mpl.java:305)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.invoke(MethodInvocationHandlerImpl.java:
179)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.sun.proxy.$Proxy24.retrieveServiceContent(Unknown Source)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl$1.actionCommand(AdminClientImpl.java:339)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl$1.actionCommand(AdminClientImpl.java:334)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.execute(VmomiClientCommand.java:103)
Jan 19 15:40:26 localhost start_fileserver.sh[1759]:         ... 10 more
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.826Z DEBUG op=1762.32: exit status 1
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.831Z ERROR op=1762.32: Install failed: Failed to register with PSC. Please check the PSC settings
provided and try again
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.831Z DEBUG [BEGIN]  [vic-product/installer/fileserver/routes.RenderTemplate:45]
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.831Z INFO  op=1762.32: render: html/index.html
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.834Z DEBUG [ END ]  [vic-product/installer/fileserver/routes.RenderTemplate:45] [3.171027ms]
Jan 19 15:40:26 localhost start_fileserver.sh[1759]: Jan 19 2022 15:40:26.834Z DEBUG [ END ]  [vic-product/installer/fileserver/routes.(*IndexHTMLRenderer).IndexHandler:52]

#### Troubleshooting attempted

I have tried using both the FQDN and IP address for our vcenter with embedded PSC. My admin account is the only one which allows me to get this far in the configuration process. Using the root account for vcenter returns invalid credentials, but they do work with the vcenter:5480 management console.

**Comment by gitloy** [comment]
I will add that I can ssh into the appliance and from there I can successfully ping both the FQDN and IP address of our vcenter/psc

**Comment by AlchemicalChef** [comment]
I'm having the same issue here as well, none of the previous troubleshooting steps have worked.

**Comment by gitloy** [comment]
@AlchemicalChef  From what I've seen on the vmware subreddit I'm pretty sure no one is working this project anymore.

**Comment by AlchemicalChef** [comment]
Yeah they want you to use Tanzu instead, but it's way more effort than I want to put in.

**Comment by lazarin** [comment]
Seems like both error logs reveal different problems,
@AlchemicalChef can you try to sync the clock on all machines, probably there's some time lag between them
@gitloy not sure in that case, just seeing that there's `Unexpected status code: 404` in library which is trying to connect to the psc :(
