### ISSUE TITLE
PSC register failure: com.vmware.vim.vmomi.client.common.UnexpectedStatusCodeException: Unexpected status code: 400

### ISSUE THREAD

**Issue by lazarin** [vmware/vic-product#771]
This is a copy of an issue [196](https://github.com/vmware/admiral/issues/196) initially opened in Admiral product:

----

Found by a customer in OVA RC3 build https://storage.googleapis.com/vic-product-ova-builds/vic-v1.2.0-rc3-ce9fca67.ova

Upon running `admiral-auth-psc-1.2.0-SNAPSHOT-command.jar --command=register --tenant=<non " .local" domain>  ... (other args)`, it fails with:

```
[0][I][2017-09-07T19:53:20.378Z][1][SsoPscCommand][register][Initializing...]
[1][I][2017-09-07T19:53:20.385Z][1][SsoPscCommand][register][Registering...]
[2][I][2017-09-07T19:53:20.409Z][1][SsoPscCommand][deleteFile][Removal of file: '/etc/vmware/psc/harbor/psc-config.keystore' result: true]
[3][I][2017-09-07T19:53:31.070Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][prepareRefresh][Refreshing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@59e5ddf: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[4][I][2017-09-07T19:53:31.097Z][1][XmlBeanDefinitionReader][loadBeanDefinitions][Loading XML bean definitions from class path resource [com/vmware/vim/binding/vmodl/context_v2.xml]]
[5][I][2017-09-07T19:53:31.294Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][doClose][Closing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@59e5ddf: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[6][I][2017-09-07T19:53:31.296Z][1][VmodlContextImpl][loadVmodlPackage][Package com.vmware.vim.binding.vmodl loaded in 243 millis]
[7][I][2017-09-07T19:53:31.296Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][prepareRefresh][Refreshing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@6e509ffa: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[8][I][2017-09-07T19:53:31.297Z][1][XmlBeanDefinitionReader][loadBeanDefinitions][Loading XML bean definitions from class path resource [com/vmware/vim/binding/vmodl/context_v2.xml]]
[9][I][2017-09-07T19:53:31.324Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][doClose][Closing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@6e509ffa: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[10][I][2017-09-07T19:53:31.324Z][1][VmodlContextImpl][loadVmodlPackage][Package com.vmware.vim.binding.vmodl loaded in 27 millis]
[11][I][2017-09-07T19:53:31.325Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][prepareRefresh][Refreshing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@6236eb5f: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[12][I][2017-09-07T19:53:31.325Z][1][XmlBeanDefinitionReader][loadBeanDefinitions][Loading XML bean definitions from class path resource [com/vmware/vim/binding/sso/context.xml]]
[13][I][2017-09-07T19:53:31.484Z][1][VmodlContextImpl$NonValidatingClassPathXmlApplicationContext][doClose][Closing com.vmware.vim.vmomi.core.types.impl.VmodlContextImpl$NonValidatingClassPathXmlApplicationContext@6236eb5f: startup date [Thu Sep 07 19:53:31 UTC 2017]; root of context hierarchy]
[14][I][2017-09-07T19:53:31.484Z][1][VmodlContextImpl][loadVmodlPackage][Package com.vmware.vim.binding.sso loaded in 159 millis]
[15][W][2017-09-07T19:53:31.559Z][1][SiteAffinityServerEndpointProvider][logWarning][CDC not configured java.lang.NoClassDefFoundError: com/vmware/identity/cdc/CdcFactory]

Exception in thread "main" com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClient
Exception: General SSO failure. Invalid host, port or tenant.
at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClientFactoryImpl.java:148)
at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminFacade.registerOrRetrieveSolutionUser(SsoAdminFacade.java:172)
at com.vmware.admiral.auth.idm.psc.saml.util.SsoPscCommand.register(SsoPscCommand.java:83)
at com.vmware.admiral.auth.idm.psc.util.PscCommand.execute(PscCommand.java:37)
at com.vmware.admiral.auth.idm.psc.util.PscCommand.main(PscCommand.java:47)
Caused by: com.vmware.vim.sso.admin.exception.InternalError: General failure.
at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.execute(VmomiClientCommand.java:211)

at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.executeEnsuringNoDomainError(VmomiClientCommand.java:217)
at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl.createServiceContent(AdminClientImpl.java:334)
at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl.<init>(AdminClientImpl.java:107)
at com.vmware.vim.sso.admin.client.vmomi.VmomiClientFactory.createAdminClient(VmomiClientFactory.java:64)
at com.vmware.vim.sso.admin.client.vmomi.VmomiClientFactory.createAdminClient(VmomiClientFactory.java:54)
at com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient(SsoAdminClientFactoryImpl.java:123)
... 4 more

Caused by: com.vmware.vim.vmomi.client.common.UnexpectedStatusCodeException: Unexpected status code: 400
at com.vmware.vim.vmomi.client.common.Response$Status.getStatus(Response.java:58)
at com.vmware.vim.vmomi.client.http.impl.HttpExchangeBase.parseResponse(HttpExchangeBase.java:150)
at com.vmware.vim.vmomi.client.http.impl.HttpExchange.run(HttpExchange.java:48)
at com.vmware.vim.vmomi.client.http.impl.HttpProtocolBindingBase.executeRunnable(HttpProtocolBindingBase.java:226)
at com.vmware.vim.vmomi.client.http.impl.HttpProtocolBindingImpl.send(HttpProtocolBindingImpl.java:109)
at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl$CallExecutor.sendCall(MethodInvocationHandlerImpl.java:581)
at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl$CallExecutor.executeCall(MethodInvocationHandlerImpl.java:562)
at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.completeCall(MethodInvocationHandlerImpl.java:344)
at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.invokeOperation(MethodInvocationHandlerImpl.java:304)
at com.vmware.vim.vmomi.client.common.impl.MethodInvocationHandlerImpl.invoke(MethodInvocationHandlerImpl.java:178)
at com.sun.proxy.$Proxy25.retrieveServiceContent(Unknown Source)
at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl$1.actionCommand(AdminClientImpl.java:339)
at com.vmware.vim.sso.admin.client.vmomi.impl.AdminClientImpl$1.actionCommand(AdminClientImpl.java:334)
at com.vmware.vim.sso.admin.client.vmomi.impl.VmomiClientCommand.execute(VmomiClientCommand.java:103)
... 10 more"
``` 

**Analysis:**

This is similar to #147, however, the stack trace shows HTTP code 400, not 404. Also, the user domain exists - upon hitting `https://{psc-hostname}/sso-adminserver/sdk/{tenant-id}`, the response is:

```
<?xml version="1.0" encoding="UTF-8" ?> 
- <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
- <soapenv:Body>
- <soapenv:Fault>
  <faultcode>ServerFaultCode</faultcode>
  <faultstring>Unexpected EOF in prolog at [row,col {unknown-source}]: [1,0]</faultstring> 
- <detail>
  <RuntimeFaultFault xsi:type="vim25:InvalidRequest" xmlns="urn:vim25" xmlns:vim25="urn:vim25" />
  </detail>
  </soapenv:Fault>
  </soapenv:Body>
  </soapenv:Envelope>
```

which according to https://github.com/vmware/admiral/issues/147#issuecomment-320801876 means that this domain exists in PSC (cc @shadjiiski)

The customer has also attempted other user domains, including AD domains. What could be missing here?

@martin-borisov @sergiosagu @lcastellano Please help triage this, thanks!

**Comment by lazarin** [comment]
[Comment](https://github.com/vmware/admiral/issues/196#issuecomment-327950469) from @lcastellano 

----

Here is what I think is happening. The Admiral psc registration command accepts an argument **tenant**. That is the domain in which the  registration command tries to create the "Solution Users" for Engine, Admiral and Harbor. The current implementation of the OVA derives the **tenant** argument from the domain name of the administrator credentials. For instance, the username part of the admin credential is: _administrator@myldap.com_. This may happen as the administrator credentials may come from a different source, for instance an Active Directory or a LADP server. Then the psc registration command is called with **tenant** set to _myladp.com_ which is where the psc registration command tries to create the "Solution Users". That fails as it should. Unfortunately I don't currently have access to a vSphere installation with those parameters to validate this is the problem. In any case a potential solution would be to add the **tenant** as a separate parameter in the OVA configuration, set that to vsphere.local by default and then provide instructions on how to locate the local domain name in case VC was installed with a local domain name different than vsphere.local.

**Comment by lazarin** [comment]
A potential temporary workaround for the customer would be to create a VC admin users in a local vSphere domain and use that user to install VIC product.

----

Given the workaround we should release note this and fix in the next release.

----

@martin-borisov do you agree about release noting. if so, @stuclem

----

@mdubya66 yes, absolutely

**Comment by stuclem** [comment]
Here's an attempt at a release note:

----


- <b>Deployment of appliance fails if vSphere administrator user is not in the `@vsphere.local` domain. [#771](https://github.com/vmware/vic/issues/771)</b><br>If your vSphere domain is not `@vsphere.local`, deployment of the appliance succeeds, but registration with the Platform Services Controller fails and vSphere Integrated Containers services do not start.   

   Workaround: Create or use an administrator account in the `@vsphere.local` domain to deploy the appliance and register it with the Platform Services Controller.

-----

@lcastellano @andrewtchin @anchal-agrawal is this OK?

**Comment by andrewtchin** [comment]
@stuclem that sounds like an accurate assessment of the current state

**Comment by lcastellano** [comment]
Yes that looks good.

**Comment by stuclem** [comment]
Thanks @lcastellano and @andrewtchin

**Comment by anchal-agrawal** [comment]
@stuclem We also have a workaround to cover the case where the user may not wish to create the `vsphere.local` domain and would like to use the existing domain. I have documented the complete workaround in a gist here: https://gist.github.com/anchal-agrawal/b80d87ee6865c4a2ee0c7b1569674c37 (lengthy, may not fit in the release note page). @andrewtchin has written a script for this workaround: https://github.com/vmware/vic-product/pull/778.

We can mention the script or the manual steps as a troubleshooting doc or KB article as well.
